
ALIVE_STATE = 1
ALIVE_COLOR = 'black'
DEAD_STATE = 0
DEAD_COLOR = 'white'

WINDOW_TITLE = "Conway's Game of Life"
CANVAS_HEIGHT_MULTIPLIER = 20
MIN_CANVAS_HEIGHT = 750

CANVAS_NO_BORDER_SIZE = 0
CANVAS_NO_HIGHLIGHT = 0
CANVAS_NO_OUTLINE = ''

UPDATE_DELAY_MS = 1000
